### PR TITLE
Add line break within tooltips

### PR DESCRIPTION
**Pull request by kenlog**
add HTML coded character

### CODE REVIEW

**Comment by creecros** [comment]
@BlueTeck 
1.2.5.1? or 1.2.6? No idea how you're doing versioning, or if it really matters...

**Comment by TimoStahl** [comment]
@creecros 

X.X.X.Y 

X was the minimum Kanboard Version and Y was a sequential number 🤔

**Comment by creecros** [comment]
Ah, pretty sure I tested it all the way down to 1.0.45, with no issue, but that was a while ago...wouldn't be surprised if it works all the way down to 1.0.38...

**Comment by creecros** [comment]
shit, I lied, works down to v1.2.4, because of `$this->app->tooltipMarkdown`

could broaden compatibility, if desired. easy fix.

**Pull request merged**
